//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Part20
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractEmployee : Employee
    {
        public Nullable<int> HourlyPay { get; set; }
        public Nullable<int> HoursWorked { get; set; }
    }
}
